version: '3.2'
services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  url-shortener:
    build: .
    container_name: url-shortener
    ports:
      - 9000:9000
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379